---
services:
  # Microsoft Visual Studio Code
  code-server:
    # Pin latest to digest so deploys are reproducible; Renovate will bump this digest.

    # renovate: datasource=docker depName=lscr.io/linuxserver/code-server
    image: lscr.io/linuxserver/code-server:latest@sha256:f0f4cc06a8c642e61299fe57b01fe2d5ded3934e923aba7456770e70a3c8cf97
    container_name: code-server
    env_file:
      - /mnt/fast/stacks/code-server/.env
    environment:
      - TZ=Europe/Dublin
      # strongly recommend running as the 'apps' account:
      # id -u apps -> 568, id -g apps -> 568 on SCALE
      - PUID=${PUID:-568}
      - PGID=${PGID:-568}
    volumes:
      # AppData Configuration Presistance Dataset
      - /mnt/fast/appdata/code-server:/config
      # Access to edit the Stacks
      - /mnt/fast/stacks:/stacks:rw
    ports:
      - "8443:8443"
    restart: unless-stopped
