---
services:
  # Microsoft Visual Studio Code
  code-server:
    # Pin latest to digest so deploys are reproducible; Renovate will bump this digest.

    # renovate: datasource=docker depName=lscr.io/linuxserver/code-server
    image: lscr.io/linuxserver/code-server:4.104.3
    pull_policy: always
    container_name: code-server
    env_file:
      - /mnt/fast/stacks/code-server/.env
    environment:
      - TZ=Europe/Dublin
      # strongly recommend running as the 'apps' account:
      # id -u apps -> 568, id -g apps -> 568 on SCALE
      - PUID=${PUID:-568}
      - PGID=${PGID:-568}
    volumes:
      # AppData Configuration Presistance Dataset
      - /mnt/fast/appdata/code-server:/config
      # Access to edit the Stacks
      - /mnt/fast/stacks:/stacks:rw
    ports:
      - "8444:8443"
    restart: unless-stopped
    labels:
      - "tsbridge.enabled=true"
      - "tsbridge.service.name=code"                   # Default: container name
      - "tsbridge.service.port=8443"                   # Port inside the container
      - "tsbridge.service.access_log=false"            # Disable access log
      - "tsbridge.service.tags=tag:dev,tag:prod"       # Override default tags
      - "tsbridge.service.insecure_skip_verify=true"   # Skip TLS cert verification (HTTPS backends only)
      - "tsbridge.service.whois_enabled=true"          # Add identity headers
      