services:
  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - t3_proxy
      - postiz
    volumes:
      - postiz_config:/config
      - postiz_uploads:/uploads
    environment:
      # Database and Redis from .env
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      
      # Core URLs
      - MAIN_URL=${MAIN_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - BACKEND_INTERNAL_URL=${BACKEND_INTERNAL_URL}
      
      # Security
      - JWT_SECRET=${JWT_SECRET}
      - IS_GENERAL=${IS_GENERAL}
      - DISABLE_REGISTRATION=${DISABLE_REGISTRATION}
      
      # Storage
      - STORAGE_PROVIDER=${STORAGE_PROVIDER}
      - UPLOAD_DIRECTORY=${UPLOAD_DIRECTORY}
      - NEXT_PUBLIC_UPLOAD_DIRECTORY=${NEXT_PUBLIC_UPLOAD_DIRECTORY}
      
      # Developer
      - NX_ADD_PLUGINS=${NX_ADD_PLUGINS}
      
      # API Limits
      - API_LIMIT=${API_LIMIT}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=t3_proxy"
      
      # HTTP Router with Authelia
      - "traefik.http.routers.postiz.entrypoints=web,websecure"
      - "traefik.http.routers.postiz.rule=Host(`social.deercrest.info`)"
      - "traefik.http.routers.postiz.middlewares=chain-authelia@file"
      - "traefik.http.routers.postiz.service=postiz"
      - "traefik.http.services.postiz.loadbalancer.server.port=5000"
    depends_on:
      postiz_postgres:
        condition: service_healthy
      postiz_redis:
        condition: service_healthy

  postiz_postgres:
    image: postgres:17-alpine
    container_name: postiz_postgres
    restart: unless-stopped
    networks:
      - postiz
    volumes:
      - postiz_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  postiz_redis:
    image: redis:7.2-alpine
    container_name: postiz_redis
    restart: unless-stopped
    networks:
      - postiz
    volumes:
      - postiz_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
