# Jellyfin - Free Open-Source Media Server
#
# Purpose:
#   Self-hosted media streaming platform for movies, TV shows, music, and photos
#   Alternative to Plex and Emby with no premium features or tracking
#
# Key Features:
#   - Hardware-accelerated transcoding (VA-API on AMD Radeon 890M)
#   - Multi-user support with individual libraries and watch history
#   - Apps for all platforms (Android, iOS, Roku, Fire TV, etc.)
#   - Live TV and DVR with HDHomeRun/M3U support
#   - Subtitle support and automatic downloading
#   - Rich metadata from TMDb, TVDb, MusicBrainz
#   - Plugin system (intro skipper, playback reporting, etc.)
#
# Hardware Acceleration:
#   AMD Ryzen AI 9 HX PRO 370 with AMD Radeon 890M GPU
#   VA-API transcoding for H.264, HEVC 10-bit, VP9 10-bit
#   Reduces CPU load and power consumption
#
# Access:
#   URL: https://jellyfin.deercrest.info
#   Middleware: chain-no-auth (public access for all users)
#   Local Discovery: Port 7359/UDP, 1900/UDP
#
networks:
  iot_macvlan:
    external: true

services:

  # Jellyfin - Media Server
  # Hardware: AMD Ryzen AI 9 HX PRO 370 with AMD Radeon 890M GPU
  # Jellyfin Transcoding Settings:
  #   - Hardware acceleration: VAAPI
  #   - Enable decoding for:
  #     - H264 format: yes
  #     - HEVC format: no
  #     - MPEG2 format: no
  #     - VC1 format: no
  #     - VP8 format: no
  #     - VP9 format: no
  #     - AV1 format: no
  #     - HEVC 10bit format: yes
  #     - VP9 10bit format: yes
  #   - Enable ecoding: yes
  #      - HEVC format: no
  #      - AV1 format: no
  #   - Tone mapping: no
  #      - Tone mapping algorithm: BT.2390
  #      - Tone mapping mode: Auto
  #      - Tone mapping range: Auto
  #      - Tone mapping desat: 0
  #      - Tone mapping peak: 100
  #   - Transcoding thread count: Auto
  jellyfin:
    hostname: jellyfin
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["media", "all"]
    # user: $PUID:$PGID
    group_add:
      - "44"   # video group for AMD GPU access
      - "110"  # render group for AMD Radeon 890M GPU access
    networks:
      iot_macvlan:
        ipv4_address: 172.16.1.76
      t3_proxy:
    ports:
      - target: 8096
        published: 8096
        protocol: tcp
        mode: host
      - target: 8920
        published: 8920
        protocol: tcp
        mode: host
      - 7359:7359/udp #optional local discovery
      - 1900:1900/udp #optional
    environment:
      UMASK_SET: 022
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DOCKER_MODS: ghcr.io/themepark-dev/theme.park:jellyfin
      TP_THEME: organizr
      JELLYFIN_PublishedServerUrl: jellyfin.deercrest.info
      
    devices:
      # AMD Radeon 890M GPU for hardware transcoding (AMD AMF)
      # Supports H.264, HEVC (H.265), VP9, AV1 decode/encode
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro  # System timezone for scheduling
      - /mnt/fast/appdata/media/jellyfin:/config:rw  # Application config, metadata, and database
      - /mnt/tank/media:/media  # Media library (movies, TV, music, photos)
      # Transcode to RAM for better performance and reduced disk wear
      - /dev/shm:/data/transcode  # RAM disk for temporary transcoding files
    labels:
      - traefik.enable=true

      # HTTP Routers
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.deercrest.info`)
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=dns-cloudflare
      # Middlewares
      #- traefik.http.routers.jellyfin.middlewares=chain-authelia@file
      # HTTP Services
      - traefik.http.routers.jellyfin.service=jellyfin-svc
      - traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096




