services:

  # Jellyfin - Media Server
  # Hardware: AMD Ryzen AI 9 HX PRO 370 with AMD Radeon 890M GPU
  # Jellyfin Transcoding Settings:
  #   - Hardware acceleration: VAAPI
  #   - Enable decoding for:
  #     - H264 format: yes
  #     - HEVC format: no
  #     - MPEG2 format: no
  #     - VC1 format: no
  #     - VP8 format: no
  #     - VP9 format: no
  #     - AV1 format: no
  #     - HEVC 10bit format: yes
  #     - VP9 10bit format: yes
  #   - Enable ecoding: yes
  #      - HEVC format: no
  #      - AV1 format: no
  #   - Tone mapping: no
  #      - Tone mapping algorithm: BT.2390
  #      - Tone mapping mode: Auto
  #      - Tone mapping range: Auto
  #      - Tone mapping desat: 0
  #      - Tone mapping peak: 100
  #   - Transcoding thread count: Auto
  jellyfin:
    hostname: jellyfin
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["media", "all"]
    # user: $PUID:$PGID
    group_add:
      - "44"   # video group for AMD GPU access (standard on TrueNAS)
      - "107"  # render group for AMD Radeon 890M GPU access (standard on TrueNAS)
    networks:
      - t3_proxy
    ports:
      - target: 8096
        published: 8096
        protocol: tcp
        mode: host
      - target: 8920
        published: 8920
        protocol: tcp
        mode: host
      - 7359:7359/udp #optional local discovery
      - 1900:1900/udp #optional
    environment:
      UMASK_SET: 022
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DOCKER_MODS: ghcr.io/themepark-dev/theme.park:jellyfin
      TP_THEME: organizr
      JELLYFIN_PublishedServerUrl: jellyfin.deercrest.info
      
    devices:
      # AMD Radeon 890M GPU for hardware transcoding (AMD AMF)
      # Supports H.264, HEVC (H.265), VP9, AV1 decode/encode
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/fast/appdata/media/jellyfin:/config:rw
      - /mnt/tank/media:/media
      # Transcode to RAM for better performance and reduced disk wear
      - /dev/shm:/data/transcode
    labels:
      - traefik.enable=true

      # HTTP Routers
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.deercrest.info`)
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=dns-cloudflare
      # Middlewares
      #- traefik.http.routers.jellyfin.middlewares=chain-authelia@file
      # HTTP Services
      - traefik.http.routers.jellyfin.service=jellyfin-svc
      - traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096




