# Seerr - Unified Media Request Management System
#
# Purpose:
#   Unified fork of Jellyseerr and Overseerr for requesting movies and TV shows
#   Supports both Jellyfin and Plex with enhanced features and active development
#   Automatically sends approved requests to Radarr/Sonarr for download
#
# Key Features:
#   - Self-service media requests with approval workflow
#   - Jellyfin AND Plex user integration (SSO)
#   - Automatic availability checking across multiple servers
#   - Request notifications via Discord/Email/Slack/Telegram
#   - User quotas and request limits
#   - 4K/1080p quality selection
#   - Enhanced discovery and recommendations
#   - Active development (merger of Jellyseerr + Overseerr)
#
# Workflow:
#   User requests → Approval (optional) → Radarr/Sonarr → Download → Media library
#
# Access:
#   URL: https://requests.deercrest.info
#   Middleware: chain-no-auth (public access for users)
#
services:
  # Seerr - Unified media request management for Jellyfin/Plex
  # Allows users to request movies/TV shows that get automatically added to Radarr/Sonarr
  jellyseerr:
    hostname: "seerr"
    container_name: seerr
    image: ghcr.io/seerr-team/seerr:develop
    user: "568:568"  # Run as apps:apps to match TrueNAS permissions
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
    ports:
      - "5055:5055"
    volumes:
      - /mnt/fast/appdata/media/seerr/config:/app/config:rw  # Application config and database
      - /mnt/tank/media:/data:ro  # Read-only access to media library for availability checks
    environment:
      TZ: $TZ
    labels:
      - traefik.enable=true

      - traefik.http.routers.jellyseerr-rtr.entrypoints=web,websecure
      - traefik.http.routers.jellyseerr-rtr.rule=Host(`requests.deercrest.info`)
      - traefik.http.routers.jellyseerr-rtr.middlewares=chain-no-auth@file
      - traefik.http.routers.jellyseerr-rtr.tls=true
      - traefik.http.routers.jellyseerr-rtr.tls.certresolver=dns-cloudflare
      - traefik.http.routers.jellyseerr-rtr.service=jellyseerr-svc

      - traefik.http.services.jellyseerr-svc.loadbalancer.server.port=5055
