name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    env_file:
      - /mnt/fast/stacks/immich/.env
    environment:
      - TZ=${TZ}
      # Advise the server to use VAAPI when available
      - IMMICH_FFMPEG_HWACCEL=vaapi
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
      # Optional read-only import staging (uncomment .env IMPORT_PATH and line below)
      # - ${IMPORT_PATH}:/import:ro
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    devices:
      - /dev/dri:/dev/dri

  immich-machine-learning:
    #devices:
    #  - /dev/kfd:/dev/kfd
    #  - /dev/dri:/dev/dri
    container_name: immich_machine_learning
    #image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-rocm
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    env_file:
      - /mnt/fast/stacks/immich/.env
    volumes:
      - model-cache:/cache
    restart: always
    healthcheck:
      disable: false
    group_add:
      - "${VIDEO_GID}"
      - "${RENDER_GID}"
    ipc: host
    environment:
      EXECUTION_PROVIDERS: CPUExecutionProvider
      # Prefer ROCm, but fall back to CPU if ROCm fails
      # EXECUTION_PROVIDERS: ROCMExecutionProvider,CPUExecutionProvider
      # Spoof gfx1150 -> gfx1151 (present in the image’s Tensile libs)
      #HSA_OVERRIDE_GFX_VERSION: "11.5.1"
      # Persist MIOpen databases/caches (reduces first-run latency)
      #MIOPEN_USER_DB_PATH: /cache/miopen
      #MIOPEN_CACHE_DIR: /cache/miopen
      # (Optional) reduce thread pressure
      #OMP_NUM_THREADS: "4"
      IMMICH_ML_FORCE_CPU: true        # hard force CPU provider
      ROCR_VISIBLE_DEVICES:           # hide AMD GPUs from ROCm
      HIP_VISIBLE_DEVICES:            # (belt-and-suspenders)

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:41eacbe83eca995561fe43814fd4891e16e39632806253848efaf04d3c8a8b84
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always

volumes:
  model-cache: {}
