services:
  dawarich_redis:
    image: redis:7.4-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - dawarich_shared:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dawarich_db:
    image: postgis/postgis:17-3.5-alpine
    # image: imresamu/postgis:17-3.5-alpine # If you're on ARM architecture, use this image instead
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - dawarich_db_data:/var/lib/postgresql/data
      - dawarich_shared:/var/shared
    networks:
      - dawarich
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
      - dawarich_db_data:/dawarich_db_data
    networks:
      - dawarich
      - t3_proxy
    # Port binding disabled - using Traefik reverse proxy
    # ports:
    #   - "127.0.0.1:3004:3000"
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL: redis://dawarich_redis:6379
      DATABASE_HOST: dawarich_db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
      MIN_MINUTES_SPENT_IN_CITY: ${MIN_MINUTES_SPENT_IN_CITY}
      APPLICATION_HOSTS: ${APPLICATION_HOSTS}
      TIME_ZONE: ${TZ}
      APPLICATION_PROTOCOL: https
      PROMETHEUS_EXPORTER_ENABLED: ${PROMETHEUS_EXPORTER_ENABLED}
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: ${PROMETHEUS_EXPORTER_PORT}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_LOG_TO_STDOUT: true
      SELF_HOSTED: true
      STORE_GEODATA: true
      DISABLE_REGISTRATION: "false"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --no-check-certificate -qO- http://127.0.0.1:3000/api/v1/health 2>&1 | grep -q 'ok' || exit 1"]
    #   interval: 15s
    #   retries: 30
    #   start_period: 45s
    #   timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_started
      dawarich_redis:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: ${APP_CPU_LIMIT}
          memory: ${APP_MEMORY_LIMIT}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=t3_proxy"
      
      # Main router with authentication
      - "traefik.http.routers.dawarich.entrypoints=web,websecure"
      - "traefik.http.routers.dawarich.rule=Host(`findme.deercrest.info`)"
      - "traefik.http.routers.dawarich.middlewares=chain-authelia@file"
      - "traefik.http.routers.dawarich.service=dawarich"
      - "traefik.http.services.dawarich.loadbalancer.server.port=3000"

  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL: redis://dawarich_redis:6379
      DATABASE_HOST: dawarich_db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
      APPLICATION_HOSTS: ${APPLICATION_HOSTS}
      BACKGROUND_PROCESSING_CONCURRENCY: ${BACKGROUND_PROCESSING_CONCURRENCY}
      APPLICATION_PROTOCOL: https
      PROMETHEUS_EXPORTER_ENABLED: ${PROMETHEUS_EXPORTER_ENABLED}
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: ${PROMETHEUS_EXPORTER_PORT}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_LOG_TO_STDOUT: true
      SELF_HOSTED: true
      STORE_GEODATA: true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    # healthcheck:
    #   test: ["CMD-SHELL", "pgrep -f sidekiq"]
    #   interval: 10s
    #   retries: 30
    #   start_period: 30s
    #   timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_started
      dawarich_redis:
        condition: service_started
      dawarich_app:
        condition: service_started
