services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    container_name: cadvisor
    hostname: cadvisor
    restart: unless-stopped
    privileged: true
    networks:
      - t3_proxy
    # ports:
    #   - "8080:8080"  # Uncomment for direct access
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    command:
      - '--housekeeping_interval=30s'
      - '--docker_only=true'
      - '--disable_metrics=percpu,process,referenced_memory,tcp,udp,advtcp,sched,hugetlb,resctrl'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.${DOMAINNAME}`)"
      - "traefik.http.routers.cadvisor.entrypoints=websecure"
      - "traefik.http.routers.cadvisor.tls=true"
      - "traefik.http.routers.cadvisor.tls.certresolver=letsencrypt"
      - "traefik.http.routers.cadvisor.middlewares=chain-authelia@file"
      - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"

networks:
  t3_proxy:
    external: true
