# FlareSolverr - Cloudflare and Anti-Bot Bypass Proxy
#
# Purpose:
#   Acts as a proxy server to bypass Cloudflare protection and bot detection
#   Used by Prowlarr/Jackett to access indexers with Cloudflare challenges
#
# Key Features:
#   - Cloudflare challenge solver (JavaScript, CAPTCHA)
#   - User-Agent rotation
#   - Cookie persistence
#   - Browser automation (headless Chrome)
#   - Request queueing
#
# How It Works:
#   Prowlarr → FlareSolverr → Solves Challenge → Returns Cookies → Prowlarr accesses indexer
#
# Access:
#   URL: https://flaresolverr.deercrest.info (web UI)
#   Middleware: chain-authelia (protected - admin only)
#   Internal URL: http://flaresolverr:8191 (used by Prowlarr)
#
services:
  # FlareSolverr - Proxy server to bypass Cloudflare protection
  # Used by Prowlarr to access protected indexers
  flaresolverr:
    hostname: "flaresolverr"
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
    ports:
      - "8191:8191"
    environment:
      LOG_LEVEL: info
      LOG_HTML: false
      CAPTCHA_SOLVER: none
      TZ: $TZ
    labels:
      - traefik.enable=true

      - traefik.http.routers.flaresolverr-rtr.entrypoints=web,websecure
      - traefik.http.routers.flaresolverr-rtr.rule=Host(`flaresolverr.deercrest.info`)
      - traefik.http.routers.flaresolverr-rtr.middlewares=chain-authelia@file
      - traefik.http.routers.flaresolverr-rtr.tls=true
      - traefik.http.routers.flaresolverr-rtr.tls.certresolver=dns-cloudflare
      - traefik.http.routers.flaresolverr-rtr.service=flaresolverr-svc

      - traefik.http.services.flaresolverr-svc.loadbalancer.server.port=8191
