# qBittorrent - BitTorrent Client with Web UI
#
# Purpose:
#   Downloads torrent files for media acquisition
#   Primary download client for torrent-based content
#
# Key Features:
#   - Web-based UI for remote management
#   - Category-based organization
#   - RSS feed downloader with filters
#   - Sequential downloading
#   - IP filtering and encryption
#   - Torrent creation and management
#   - Speed limits and scheduling
#   - API for integration with Radarr/Sonarr
#
# Workflow:
#   Radarr/Sonarr → Sends torrent to qBittorrent → Downloads → Seeds → Moves to category folder
#
# Access:
#   URL: https://qbittorrent.deercrest.info
#   Middleware: chain-authelia (protected - admin access)
#
services:
  # qBittorrent - BitTorrent download client
  qbittorrent:
    hostname: "qbittorrent"
    container_name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent:5.1.2-r3-ls421
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["apps", "downloads", "all"]
    networks:
      - t3_proxy
    ports:
      - "7889:7889"
    volumes:
      - /mnt/fast/appdata/arrs/qbittorrent/config:/config:rw  # Application config, torrents, and state
      - /mnt/fast/appdata/arrs/qbittorrent/arr-scripts:/custom-cont-init.d  # Custom initialization scripts
      - /mnt/tank/downloads:/downloads:rw  # Download output directory (incomplete and complete)
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 002
      DOCKER_MODS: ghcr.io/themepark-dev/theme.park:qbittorrent
      TP_THEME: organizr
    labels:
      - traefik.enable=true

      - traefik.http.routers.qbittorrent.entrypoints=web,websecure
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.deercrest.info`)
      - traefik.http.routers.qbittorrent.middlewares=chain-authelia@file
      - traefik.http.routers.qbittorrent.tls=true
      - traefik.http.routers.qbittorrent.tls.certresolver=dns-cloudflare
      - traefik.http.routers.qbittorrent.service=qbittorrent-svc

      # Bypass router for mobile apps (priority 100 evaluated before main router)
      - traefik.http.routers.qbittorrent-bypass.entrypoints=websecure
      - traefik.http.routers.qbittorrent-bypass.rule=Host(`qbittorrent.deercrest.info`) && Header(`auth-bypass-key`, `$QBITTORRENT_AUTH_BYPASS_KEY`) # Bypass Auth for mobile apps
      - traefik.http.routers.qbittorrent-bypass.middlewares=chain-no-auth@file
      - traefik.http.routers.qbittorrent-bypass.priority=100
      - traefik.http.routers.qbittorrent-bypass.tls=true
      - traefik.http.routers.qbittorrent-bypass.tls.certresolver=dns-cloudflare
      - traefik.http.routers.qbittorrent-bypass.service=qbittorrent-svc

      - traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8080



