# Sonarr - TV Show Collection Manager and Downloader
#
# Purpose:
#   Automatically searches, downloads, and organizes TV shows and episodes
#   Tracks airdates and monitors for new episodes
#
# Key Features:
#   - Automated TV show/episode search via torrent/Usenet
#   - Calendar tracking for upcoming episodes
#   - Season pack and daily/anime show support
#   - Quality profiles (4K, 1080p, 720p)
#   - Custom format scoring (WEB-DL, BluRay, x265)
#   - Series and season monitoring
#   - Automatic renaming (S01E01 format)
#   - Integration with lists (Trakt, TMDb, TVDb)
#
# Workflow:
#   Add show → Monitor airdate → Search via Prowlarr → Download → Import → Rename → Notify
#
# Access:
#   URL: https://sonarr.deercrest.info
#   Middleware: chain-authelia (protected - admin access)
#   Bypass URL: Header-based bypass for mobile apps (Helmarr/LunaSea)
#
services:
  # Sonarr - TV Shows Management
  # Set url_base in sonarr settings if using PathPrefix
  sonarr:
    hostname: "sonarr"
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:develop
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["media", "arrs", "all"]
    networks:
      - t3_proxy
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro  # System timezone
      - /mnt/fast/appdata/arrs/sonarr/config:/config:rw  # Application config and database
      - /mnt/tank/downloads:/downloads:rw  # Download client output directory
      - /mnt/tank/media:/media:rw  # TV show library destination
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UMASK_SET: 002
      DOCKER_MODS: ghcr.io/themepark-dev/theme.park:sonarr
      TP_THEME: organizr
    labels:
      - traefik.enable=true

      - traefik.http.routers.sonarr-rtr.entrypoints=web,websecure
      - traefik.http.routers.sonarr-rtr.rule=Host(`sonarr.deercrest.info`)
      - traefik.http.routers.sonarr-rtr.middlewares=chain-authelia@file
      - traefik.http.routers.sonarr-rtr.tls=true
      - traefik.http.routers.sonarr-rtr.tls.certresolver=dns-cloudflare
      - traefik.http.routers.sonarr-rtr.service=sonarr-svc

      - traefik.http.routers.sonarr-bypass.entrypoints=websecure
      # - traefik.http.routers.sabnzbd-rtr-bypass.rule=Host(`sabnzbd.deercrest.info`) && Query(`apikey`, `$SONARR_API_KEY`)
      - traefik.http.routers.sonarr-bypass.rule=Host(`sonarr.deercrest.info`) && Header(`auth-bypass-key`, `$SONARR_AUTH_BYPASS_KEY`) # Bypass Auth for mobile apps
      - traefik.http.routers.sonarr-bypass.middlewares=chain-no-auth@file
      - traefik.http.routers.sonarr-bypass.tls=true
      - traefik.http.routers.sonarr-bypass.tls.certresolver=dns-cloudflare
      - traefik.http.routers.sonarr-bypass.priority=100
      - traefik.http.routers.sonarr-bypass.service=sonarr-svc

      - traefik.http.services.sonarr-svc.loadbalancer.server.port=8989


  # Sonarr Exporter - Sonarr metrics for Prometheus
  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:latest
    container_name: sonarr-exporter
    security_opt:
      - no-new-privileges:true
    restart: "no"
    # profiles: ["all", "media", "arrs"]
    networks:
      - t3_proxy
    ports:
      - "9708:9708"
    environment:
      PORT: 9708
      URL: "http://sonarr:8989"
      APIKEY: $SONARR_API_KEY
      ENABLE_ADDITIONAL_METRICS: TRUE
    command: ["sonarr"]

