version: "3.9"

services:
  #  minecraft-java:
  #    container_name: minecraft_java
  #    image: itzg/minecraft-server:latest
  #    restart: unless-stopped
  #    tty: true
  #    stdin_open: true
  #    environment:
  #     EULA: 'true'
  #      TYPE: "PAPER"
  #      PLUGINS: |
  #       https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
  #        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
  #      MODE: "creative"
  #      MOTD: "Minecraft Java Edition with Geyser and Floodgate"
  #      MEMORY: 4G
  #     ENABLE_RCON: "true"
  #      RCON_PASSWORD: "testing"
  #     RCON_CMDS_STARTUP:  |-
  #        /gamerule doFireTick false
  #   volumes:
  #     - /srv/appdata/minecraft/java:/data
  #   network_mode: service:tailscale
  #   depends_on:
  #     tailscale:
  #       condition: service_healthy

  minecraft-vanilla:
    container_name: minecraft_vanilla
    image: itzg/minecraft-bedrock-server:2025.9.0
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      EULA: 'true'
      GAMEMODE: creative
      SERVER_NAMEi: vanilla
      SERVER_PORT: 19132
      SERVER_PORT_V6: 19133
      ALLOW_CHEATS: true
      DEFAULT_PLAYER_PERMISSION_LEVEL: operator
    volumes:
      - /mnt/fast/appdata/minecraft/bedrock:/data
#    network_mode: service:tailscale
#    depends_on:
#      tailscale:
#        condition: service_healthy

  minecraft-yggdrasil:
    container_name: minecraft_yggdrasil
    image: itzg/minecraft-bedrock-server:2025.9.0
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      EULA: 'true'
      SERVER_NAME: yggdrasil
      SERVER_PORT: 19134
      SERVER_PORT_V6: 19135
      ALLOW_CHEATS: true
      DEFAULT_PLAYER_PERMISSION_LEVEL: operator
      LEVEL_NAME: "Yggdrasil"
    volumes:
      - /mnt/fast/appdata/minecraft/yggdrasil:/data
#    network_mode: service:tailscale
#    depends_on:
#      tailscale:
#        condition: service_healthy


#  tailscale:
#    container_name: tailscale_minecraft
#    image: ghcr.io/tailscale/tailscale:latest
#    restart: unless-stopped
#    #network_mode: service:minecraft
#    cap_add:
#      - NET_ADMIN
#      - SYS_MODULE
#      - NET_RAW
#    volumes:
#      - /srv/appdata/tailscale:/state/
#    devices:
#      - /dev/net/tun:/dev/net/tun
#    environment:
#      TS_HOSTNAME: minecraft
#      TS_STATE_DIR: /state/
#      TS_USERSPACE: 'false'
#      TS_DEBUG_FIREWALL_MODE: nftables
#      # TS_AUTHKEY=tskey-auth-ferqr3rweafaf-32414124124124214214WA
#    healthcheck:
#      test: ["CMD-SHELL", "tailscale status"]
#      interval: 1s
#      timeout: 5s
#      retries: 60

