# Minecraft Vanilla Server - Official Minecraft Java Edition
#
# Purpose:
#   Standard Minecraft Java Edition server accessible via Tailscale
#   Provides vanilla gameplay experience without modifications
#
# Key Features:
#   - Official Minecraft server (no mods or plugins)
#   - Tailscale networking for secure remote access
#   - Automatic backups and world persistence
#   - Server properties customization
#   - Whitelist and operator management
#
# Workflow:
#   Players connect via Tailscale → Server validates → Join world → Auto-save periodically
#
# Access:
#   Tailscale hostname: mc-vanilla
#   Tags: tag:games
#   Port: 25565 (Minecraft default)
#

services:
  minecraft-vanilla:
    # renovate: datasource=docker depName=itzg/minecraft-bedrock-server
    image: itzg/minecraft-bedrock-server:2025.12.2
    container_name: mc_vanilla
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "19132:19132/udp"  # Bedrock main port
      - "19133:19133/udp"  # Bedrock IPv6 port
    environment:
      EULA: "true"
      GAMEMODE: "creative"
      SERVER_NAME: "vanilla"
      SERVER_PORT: 19132
      SERVER_PORT_V6: 19133
      ALLOW_CHEATS: "true"
      DEFAULT_PLAYER_PERMISSION_LEVEL: "operator"
    volumes:
      - /mnt/fast/appdata/minecraft/bedrock:/data
    labels:
      # Expose to Tailscale via tsbridge (no sidecar needed!)
      - tsbridge.enabled=true
      - tsbridge.hostname=mc-vanilla
      - tsbridge.backend=mc_vanilla:19132
      - tsbridge.tags=tag:games



