# Minecraft Yggdrasil Server - Modded Minecraft Instance
#
# Purpose:
#   Custom Minecraft server with Yggdrasil authentication via Tailscale
#   Supports modded gameplay and custom authentication
#
# Key Features:
#   - Custom authentication system (Yggdrasil)
#   - Mod support and custom plugins
#   - Tailscale networking for secure access
#   - Independent world and configuration
#   - Custom server properties
#
# Workflow:
#   Players authenticate → Connect via Tailscale → Join modded server → Play with mods
#
# Access:
#   Tailscale hostname: mc-ygg
#   Tags: tag:games
#   Port: 25565 (Minecraft default)
#

services:
  minecraft-yggdrasil:
    # renovate: datasource=docker depName=itzg/minecraft-bedrock-server
    image: itzg/minecraft-bedrock-server:2026.2.2
    container_name: mc_yggdrasil
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "19142:19132/udp"  # Different host port to avoid conflict with vanilla
      - "19143:19133/udp"
    environment:
      EULA: "true"
      SERVER_NAME: "yggdrasil"
      SERVER_PORT: 19132
      SERVER_PORT_V6: 19133
      ALLOW_CHEATS: "true"
      DEFAULT_PLAYER_PERMISSION_LEVEL: "operator"
      LEVEL_NAME: "Yggdrasil"
      LEVEL_TYPE: "DEFAULT"
      DIFFICULTY: "peaceful"
    volumes:
      - /mnt/fast/appdata/minecraft/yggdrasil:/data
    labels:
      # Expose to Tailscale via tsbridge (no sidecar needed!)
      - tsbridge.enabled=true
      - tsbridge.hostname=mc-ygg
      - tsbridge.service.port=19132
      - tsbridge.tags=tag:games



