# Oxidized - Network Device Configuration Backup
#
# Purpose:
#   Automated backup and version control for network device configurations
#   Supports routers, switches, firewalls from multiple vendors
#
# Key Features:
#   - Multi-vendor device support (Cisco, Juniper, Mikrotik, etc.)
#   - Git-based version control for config changes
#   - Scheduled configuration pulls
#   - Web UI for viewing configs and diffs
#   - REST API for automation integration
#   - Email/webhook notifications on changes
#
# Workflow:
#   Schedule → SSH/Telnet to devices → Pull config → Git commit → Notify changes
#
# Access:
#   URL: https://oxidized.deercrest.info
#   Middleware: chain-authelia (protected - admin only)
#

services:

  oxidized:
    container_name: oxidized
    image: docker.io/oxidized/oxidized:latest
    # Run oxidized with the TrueNAS apps UID so it can write to host-mounted
    # config and ssh directories owned by 568:568.
    restart: unless-stopped
    # user: 0:0
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "8888:8888"
    volumes:
      - /mnt/fast/appdata/automation/oxidized/config:/home/oxidized/.config/oxidized
      - /mnt/fast/appdata/automation/oxidized/ssh:/home/oxidized/.ssh
    environment:
      # Reload hosts list once per day
      CONFIG_RELOAD_INTERVAL: 86400
      # # Needed when you push to a remote git repository
      # OXIDIZED_SSH_PASSPHRASE: xxxxPassphasexxxx
    labels:
      - traefik.enable=true
      - traefik.http.routers.oxidixed.entrypoints=web,websecure
      - traefik.http.routers.oxidized.rule=Host(`oxidized.deercrest.info`)
      - traefik.http.routers.oxidized.middlewares=chain-authelia@file
      - traefik.http.routers.oxidized.tls=true
      - traefik.http.routers.oxidized.tls.certresolver=dns-cloudflare
      - traefik.http.routers.oxidized.service=oxidized
      - traefik.http.services.oxidized.loadbalancer.server.port=8888

