# Tesla Static - Tesla Fleet API Public Key Server
#
# Purpose:
#   Serves Tesla Fleet API public key for vehicle authentication
#   Required for Home Assistant Tesla integration
#
# Key Features:
#   - Static file server for .well-known directory
#   - Tesla Fleet API public key hosting
#   - HTTPS with valid SSL certificate
#   - High priority routing for .well-known path
#
# Workflow:
#   Tesla API → Verify domain → Fetch .well-known/appspecific/com.tesla.3p.public-key.pem
#
# Access:
#   URL: https://hass.deercrest.info/.well-known
#   Middleware: chain-no-auth (public - Tesla API needs access)
#

services:
  tesla-static:
    image: nginx:1.29.4-alpine
    container_name: tesla-static
    restart: unless-stopped
    networks:
      - t3_proxy
    volumes:
      # This maps your host directory containing the .well-known folder
      - /mnt/fast/appdata/automation/tesla-static:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tesla-public-key.rule=Host(`hass.deercrest.info`) && PathPrefix(`/.well-known`)"
      - "traefik.http.routers.tesla-public-key.entrypoints=websecure"
      - "traefik.http.routers.tesla-public-key.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.tesla-public-key.priority=100"
      - "traefik.http.services.tesla-public-key.loadbalancer.server.port=80"

